import type { AuthorizedPersonnelBreakdown } from "@/types/ship";

export const AUTHORIZED_PERSONNEL: Record<string, AuthorizedPersonnelBreakdown> = {
  "ต.111": { officers: 5, seniorNcos: 4, pettyOfficers: 16, conscripts: 3 },
  "ต.112": { officers: 5, seniorNcos: 4, pettyOfficers: 16, conscripts: 3 },
  "ต.113": { officers: 5, seniorNcos: 4, pettyOfficers: 16, conscripts: 3 },
  "ต.114": { officers: 5, seniorNcos: 5, pettyOfficers: 18, conscripts: 2 },
  "ต.115": { officers: 5, seniorNcos: 5, pettyOfficers: 18, conscripts: 2 },
  "ต.991": { officers: 5, seniorNcos: 5, pettyOfficers: 17, conscripts: 2 },
  "ต.992": { officers: 5, seniorNcos: 5, pettyOfficers: 17, conscripts: 2 },
  "ต.993": { officers: 5, seniorNcos: 5, pettyOfficers: 17, conscripts: 2 },
  "ต.994": { officers: 5, seniorNcos: 5, pettyOfficers: 19, conscripts: 2 },
  "ต.995": { officers: 5, seniorNcos: 5, pettyOfficers: 19, conscripts: 2 },
  "ต.996": { officers: 5, seniorNcos: 5, pettyOfficers: 19, conscripts: 2 },
  "ต.997": { officers: 5, seniorNcos: 5, pettyOfficers: 19, conscripts: 2 },
  "ต.998": { officers: 5, seniorNcos: 5, pettyOfficers: 19, conscripts: 2 },
  "ต.81": { officers: 5, seniorNcos: 5, pettyOfficers: 17, conscripts: 4 },
  "ต.82": { officers: 5, seniorNcos: 5, pettyOfficers: 17, conscripts: 4 },
  "ต.83": { officers: 5, seniorNcos: 5, pettyOfficers: 17, conscripts: 4 },
  "ต.227": { officers: 1, seniorNcos: 2, pettyOfficers: 6, conscripts: 0 },
  "ต.228": { officers: 1, seniorNcos: 2, pettyOfficers: 6, conscripts: 0 },
  "ต.229": { officers: 1, seniorNcos: 2, pettyOfficers: 6, conscripts: 0 },
  "ต.230": { officers: 1, seniorNcos: 2, pettyOfficers: 6, conscripts: 0 },
  "ต.232": { officers: 1, seniorNcos: 2, pettyOfficers: 6, conscripts: 0 },
  "ต.233": { officers: 1, seniorNcos: 2, pettyOfficers: 6, conscripts: 0 },
  "ต.234": { officers: 1, seniorNcos: 2, pettyOfficers: 6, conscripts: 0 },
  "ต.235": { officers: 1, seniorNcos: 2, pettyOfficers: 6, conscripts: 0 },
  "ต.236": { officers: 1, seniorNcos: 2, pettyOfficers: 6, conscripts: 0 },
  "ต.237": { officers: 1, seniorNcos: 2, pettyOfficers: 6, conscripts: 0 },
  "ต.261": { officers: 1, seniorNcos: 2, pettyOfficers: 6, conscripts: 0 },
  "ต.262": { officers: 1, seniorNcos: 2, pettyOfficers: 6, conscripts: 0 },
  "ต.263": { officers: 1, seniorNcos: 2, pettyOfficers: 6, conscripts: 0 },
  "ต.264": { officers: 1, seniorNcos: 2, pettyOfficers: 6, conscripts: 0 },
  "ต.265": { officers: 1, seniorNcos: 2, pettyOfficers: 6, conscripts: 0 },
  "ต.266": { officers: 1, seniorNcos: 2, pettyOfficers: 6, conscripts: 0 },
  "ต.267": { officers: 1, seniorNcos: 2, pettyOfficers: 6, conscripts: 0 },
  "ต.268": { officers: 1, seniorNcos: 2, pettyOfficers: 6, conscripts: 0 },
  "ต.269": { officers: 1, seniorNcos: 2, pettyOfficers: 6, conscripts: 0 },
  "ต.270": { officers: 1, seniorNcos: 2, pettyOfficers: 6, conscripts: 0 },
  "ต.271": { officers: 1, seniorNcos: 2, pettyOfficers: 6, conscripts: 0 },
  "ต.272": { officers: 1, seniorNcos: 2, pettyOfficers: 6, conscripts: 0 },
  "ต.273": { officers: 1, seniorNcos: 2, pettyOfficers: 6, conscripts: 0 },
  "ต.274": { officers: 1, seniorNcos: 2, pettyOfficers: 6, conscripts: 0 },
};

export const PERSONNEL_FIELDS = [
  { key: "officers", label: "นายทหาร" },
  { key: "seniorNcos", label: "พันจ่า" },
  { key: "pettyOfficers", label: "จ่า" },
  { key: "conscripts", label: "พลทหาร" },
] as const;
