begin;

create type public.cris_role as enum ('commander', 'admin', 'ship');

create table public.ships (
  id text primary key,
  hull_number text not null unique,
  payload jsonb not null,
  dataset_id text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  role public.cris_role not null,
  ship_id text references public.ships(id),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint ship_role_requires_ship check (
    (role = 'ship' and ship_id is not null) or
    (role <> 'ship' and ship_id is null)
  )
);

create table public.ship_overlay (
  ship_id text primary key references public.ships(id) on delete cascade,
  crew integer,
  propulsion text check (propulsion in ('Operational', 'Limited', 'Not Ready') or propulsion is null),
  radar text check (radar in ('Operational', 'Limited', 'Not Ready') or radar is null),
  communication text check (communication in ('Operational', 'Limited', 'Not Ready') or communication is null),
  navigation text check (navigation in ('Operational', 'Limited', 'Not Ready') or navigation is null),
  weapon text check (weapon in ('Operational', 'Limited', 'Not Ready') or weapon is null),
  rhib text check (rhib in ('Operational', 'Limited', 'Not Ready', 'Not Installed') or rhib is null),
  eoir text check (eoir in ('Operational', 'Limited', 'Not Ready', 'Not Installed') or eoir is null),
  major_deficiencies text not null default '',
  mission_limitations text not null default '',
  updated_at text,
  updated_by uuid references auth.users(id),
  saved_at timestamptz not null default now()
);

create table public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  ship_id text not null references public.ships(id),
  field text not null,
  old_value jsonb,
  new_value jsonb,
  changed_at timestamptz not null default now()
);

create index users_role_idx on public.users(role);
create index users_ship_id_idx on public.users(ship_id);
create index audit_logs_ship_id_changed_at_idx on public.audit_logs(ship_id, changed_at desc);
create index audit_logs_user_id_changed_at_idx on public.audit_logs(user_id, changed_at desc);

create or replace function public.current_cris_role()
returns public.cris_role
language sql
stable
security definer
set search_path = public
as $$
  select role from public.users where id = (select auth.uid()) and active = true;
$$;

create or replace function public.current_cris_ship_id()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select ship_id from public.users where id = (select auth.uid()) and active = true;
$$;

revoke all on function public.current_cris_role() from public;
revoke all on function public.current_cris_ship_id() from public;
grant execute on function public.current_cris_role() to authenticated;
grant execute on function public.current_cris_ship_id() to authenticated;

alter table public.ships enable row level security;
alter table public.users enable row level security;
alter table public.ship_overlay enable row level security;
alter table public.audit_logs enable row level security;

create policy ships_select_by_role
on public.ships for select to authenticated
using (
  public.current_cris_role() in ('admin', 'commander') or
  (public.current_cris_role() = 'ship' and id = public.current_cris_ship_id())
);

create policy users_select_self_or_admin
on public.users for select to authenticated
using (
  id = (select auth.uid()) or
  public.current_cris_role() = 'admin'
);

create policy overlays_select_by_role
on public.ship_overlay for select to authenticated
using (
  public.current_cris_role() in ('admin', 'commander') or
  (public.current_cris_role() = 'ship' and ship_id = public.current_cris_ship_id())
);

create policy audit_select_admin_only
on public.audit_logs for select to authenticated
using (public.current_cris_role() = 'admin');

grant select on public.ships, public.users, public.ship_overlay to authenticated;
grant select on public.audit_logs to authenticated;
revoke insert, update, delete on public.ships, public.users, public.ship_overlay, public.audit_logs from anon, authenticated;

create or replace function public.audit_ship_overlay_changes()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  field_name text;
  old_record jsonb := case when tg_op = 'INSERT' then '{}'::jsonb else to_jsonb(old) end;
  new_record jsonb := to_jsonb(new);
  audited_fields constant text[] := array[
    'crew', 'propulsion', 'radar', 'communication', 'navigation',
    'weapon', 'rhib', 'eoir', 'major_deficiencies',
    'mission_limitations', 'updated_at'
  ];
begin
  foreach field_name in array audited_fields loop
    if (old_record -> field_name) is distinct from (new_record -> field_name) then
      insert into public.audit_logs(user_id, ship_id, field, old_value, new_value)
      values ((select auth.uid()), new.ship_id, field_name, old_record -> field_name, new_record -> field_name);
    end if;
  end loop;
  return new;
end;
$$;

create trigger audit_ship_overlay
after insert or update on public.ship_overlay
for each row execute function public.audit_ship_overlay_changes();

create or replace function public.patch_ship_overlay(
  p_ship_id text,
  p_patch jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  caller_role public.cris_role := public.current_cris_role();
  permitted_fields constant text[] := array[
    'crew', 'propulsion', 'radar', 'communication', 'navigation',
    'weapon', 'rhib', 'eoir', 'major_deficiencies',
    'mission_limitations', 'updated_at'
  ];
  supplied_field text;
begin
  if caller_role is null then
    raise exception 'inactive or missing CRIS profile' using errcode = '42501';
  end if;

  if caller_role = 'commander' then
    raise exception 'commander role is read only' using errcode = '42501';
  end if;

  if caller_role = 'ship' and p_ship_id <> public.current_cris_ship_id() then
    raise exception 'ship isolation violation' using errcode = '42501';
  end if;

  if not exists (select 1 from public.ships where id = p_ship_id) then
    raise exception 'unknown ship' using errcode = '22023';
  end if;

  for supplied_field in select jsonb_object_keys(p_patch) loop
    if not (supplied_field = any(permitted_fields)) then
      raise exception 'field % is not editable', supplied_field using errcode = '22023';
    end if;
  end loop;

  insert into public.ship_overlay (
    ship_id, crew, propulsion, radar, communication, navigation, weapon,
    rhib, eoir, major_deficiencies, mission_limitations, updated_at,
    updated_by, saved_at
  )
  values (
    p_ship_id,
    case when p_patch ? 'crew' then (p_patch ->> 'crew')::integer else null end,
    p_patch ->> 'propulsion',
    p_patch ->> 'radar',
    p_patch ->> 'communication',
    p_patch ->> 'navigation',
    p_patch ->> 'weapon',
    p_patch ->> 'rhib',
    p_patch ->> 'eoir',
    coalesce(p_patch ->> 'major_deficiencies', ''),
    coalesce(p_patch ->> 'mission_limitations', ''),
    p_patch ->> 'updated_at',
    (select auth.uid()),
    now()
  )
  on conflict (ship_id) do update set
    crew = case when p_patch ? 'crew' then (p_patch ->> 'crew')::integer else ship_overlay.crew end,
    propulsion = case when p_patch ? 'propulsion' then p_patch ->> 'propulsion' else ship_overlay.propulsion end,
    radar = case when p_patch ? 'radar' then p_patch ->> 'radar' else ship_overlay.radar end,
    communication = case when p_patch ? 'communication' then p_patch ->> 'communication' else ship_overlay.communication end,
    navigation = case when p_patch ? 'navigation' then p_patch ->> 'navigation' else ship_overlay.navigation end,
    weapon = case when p_patch ? 'weapon' then p_patch ->> 'weapon' else ship_overlay.weapon end,
    rhib = case when p_patch ? 'rhib' then p_patch ->> 'rhib' else ship_overlay.rhib end,
    eoir = case when p_patch ? 'eoir' then p_patch ->> 'eoir' else ship_overlay.eoir end,
    major_deficiencies = case when p_patch ? 'major_deficiencies' then coalesce(p_patch ->> 'major_deficiencies', '') else ship_overlay.major_deficiencies end,
    mission_limitations = case when p_patch ? 'mission_limitations' then coalesce(p_patch ->> 'mission_limitations', '') else ship_overlay.mission_limitations end,
    updated_at = case when p_patch ? 'updated_at' then p_patch ->> 'updated_at' else ship_overlay.updated_at end,
    updated_by = (select auth.uid()),
    saved_at = now();
end;
$$;

revoke all on function public.patch_ship_overlay(text, jsonb) from public;
grant execute on function public.patch_ship_overlay(text, jsonb) to authenticated;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'ship_overlay'
  ) then
    alter publication supabase_realtime add table public.ship_overlay;
  end if;
end;
$$;

insert into storage.buckets(id, name, public)
values ('cris-imports', 'cris-imports', false)
on conflict (id) do nothing;

create policy cris_imports_admin_select
on storage.objects for select to authenticated
using (bucket_id = 'cris-imports' and public.current_cris_role() = 'admin');

create policy cris_imports_admin_insert
on storage.objects for insert to authenticated
with check (bucket_id = 'cris-imports' and public.current_cris_role() = 'admin');

create policy cris_imports_admin_update
on storage.objects for update to authenticated
using (bucket_id = 'cris-imports' and public.current_cris_role() = 'admin')
with check (bucket_id = 'cris-imports' and public.current_cris_role() = 'admin');

create policy cris_imports_admin_delete
on storage.objects for delete to authenticated
using (bucket_id = 'cris-imports' and public.current_cris_role() = 'admin');

commit;
